defaults:
  - /experiment/default
  - override hydra/launcher: joblib
  - _self_

experiment_name: basic

hydra:
  sweeper:
    params:
      experiment.optimizer.lr: 0, 0.01, 0.05, 0.1
      experiment.model.theta0: "[1.,1.]"
      experiment.dataset.By: 1.0, 5.0, 10.0
