defaults:
  - /experiment/default
  - override hydra/launcher: joblib
  - _self_

experiment_name: gradient_boosting_interceptonly
model_type: gradient_boosting
covariates_for_plotting: ['ethnicity', 'marital_status']

hydra:
  sweeper:
    params:
      experiment.optimizer.lr: 0, 0.001, 0.01, 0.05
      experiment.dataset.columns: "[]"