defaults:
  - /experiment/default
  - override hydra/launcher: joblib
  - _self_

experiment_name: basic

hydra:
  sweeper:
    params:
      experiment.dataset.trend_type: sinusoidal,linear
      experiment.optimizer.lr: 0.0001,0.05,0.1,0.2,0.5
      experiment.dataset.distribution_shift_speed: 0,0.0001,0.0002,0.0005,0.001
      experiment.model.theta0: "[0.,0.,0.]"
