defaults:
  - /experiment/default
  - _self_

experiment_name: basic

hydra:
  sweeper:
    params:
      experiment.optimizer.lr: 0.001,0.01,0.1,1
      experiment.optimizer.viscosity: 0,0.01,0.1,0.9
      experiment.dataset.distribution_shift_speed: 0,0.0001,0.0002,0.0005,0.001
      experiment.model.theta0: "[0.,0.,0.],[1.,1.,1.]"
