defaults:
  - /experiment/default
  - override hydra/launcher: joblib
  - _self_

experiment_name: gradient_boosting_ethnicity_marital
model_type: gradient_boosting

hydra:
  sweeper:
    params:
      experiment.optimizer.lr: 0, 0.001, 0.01, 0.05
      experiment.optimizer.viscosity: 0,0.1,0.5,0.9
      experiment.dataset.columns: "['ethnicity', 'marital_status']"