defaults:
  - /experiment/default
  - override hydra/launcher: joblib
  - _self_

experiment_name: gradient_boosting_sex
model_type: gradient_boosting

hydra:
  sweeper:
    params:
      experiment.optimizer.lr: 0, 0.05, 0.1, 0.5, 1
      experiment.dataset.columns: "['CODE_GENDER']"